### ISSUE TITLE
Installation Failure: PyTorch 1.12.1 with CUDA 116 Not Available in Package Index

### ISSUE THREAD

**Issue by stevie86** [zackees/transcribe-anything#11]
I am trying to install PyTorch version 1.12.1 with CUDA 116 using pip but it fails because this version is not available in the PyTorch package index.

Steps to Reproduce
Run the command: `pip install torch==1.12.1 --extra-index-url https://download.pytorch.org/whl/cu116`
Expected Behavior
The PyTorch version 1.12.1 with CUDA 116 should be installed successfully.

Actual Behavior
The installation fails with the following error message:

```
ERROR: Could not find a version that satisfies the requirement torch==1.12.1 (from versions: 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.12.1
```
And a subprocess.CalledProcessError is raised.

Environment
OS: Windows 10
Python Version: 3.11
Pip Version: pip 23.2.1
Additional Context

**Comment by dakink** [comment]
what has worked for me is to change the versions in the install_cuda.py

`# Set the versions
TENSOR_VERSION = "2.0.1"
CUDA_VERSION = "cu118"
TENSOR_CUDA_VERSION = f"{TENSOR_VERSION}+{CUDA_VERSION}"
EXTRA_INDEX_URL = "https://download.pytorch.org/whl/cu118"`

**Comment by zackees** [comment]
I've got a new package isolation scheme that make `install_cuda.py` obsolete.  Just install with `pip install transcribe-anything` and everything should work now. The program is now pretty safe to install globally. Cuda-pytorch will be installed automatically if nvidia-smi is installed on your system.
