### ISSUE TITLE
Trouble running when it tries to install torch.

### ISSUE THREAD

**Issue by fivestones** [zackees/transcribe-anything#16]
Here is the error I get:

```
Running: pip install torch==2.1.2
ERROR: Could not find a version that satisfies the requirement torch==2.1.2 (from versions: 2.2.0)
ERROR: No matching distribution found for torch==2.1.2
```

I'm on MacOS on a M2 mac, with python version 3.10.10

**Comment by zackees** [comment]
Are you running the `--device cuda` or `--device cpu` by any chance?

**Comment by darioZIP** [comment]
Hello, I get exactly the same problem. Tried both CPU mode and with -device insane.

**Comment by fivestones** [comment]
> Are you running the --device cuda or --device cpu by any chance?

No, I was doing --device insane but didn't try those others.

**Comment by zackees** [comment]
Ahh... it's python 3.12. Yeah sorry, the whisper backend don't work with python 3.12. I'll add a warning so that users don't get confused.

**Comment by zackees** [comment]
Okay I added the warning and pushed a new version. Upgrade to get the warning.
