### ISSUE TITLE
please rename "hf_token" to "hf-token"

### ISSUE THREAD

**Issue by Qriist** [zackees/transcribe-anything#24]
Hello there, thanks for your hard work. I'm impressed with how easy the program was to get up and running. Great job!

I was having difficulty getting the `--hf_token` argument to function within transcribe-anything. The error message kept telling me that the `hf_token` argument was unknown.
![image](https://github.com/user-attachments/assets/27f21a41-da71-4a93-b357-4c5fe74723ce)

After some digging it seems `hf_token` was renamed to `hf-token` in an IFW [commit](https://github.com/Vaibhavs10/insanely-fast-whisper/commit/3b9234fcd1057416409cb357774b4d3e29960d28) made on Feburary 29.

The above issue seems to be the only introduced quirk. For example, I can manually pass `--hf-token=<key>` (as opposed to `--hf_token <key>`) and it _does_ appear to work (meaning the "segmenting" progress bar is visible when this is specifically passed + the `speaker` key is populated in `out.json`).
![image](https://github.com/user-attachments/assets/3a41f859-d747-418c-b603-b31edd0c4831)

However, the passed `--hf-token=<key>` does not generate the `speaker.json`, presumably because the appropriate transcribe-anything interface flag wasn't set. (Which makes perfect sense, mind you.)

At any rate, the fix should be a simple rename of the argument on your end. Thanks in advance!

**Comment by Qriist** [comment]
I have temporarily solved this by manually editing the following file:

`<python installation>\Lib\site-packages\transcribe_anything\insanely_fast_whisper.py`

I changed `--hf_token` to `--hf-token` on line 237.

In the terminal I can then run the following sample command to properly generate the speaker.json:
`transcribe-anything --hf_token <hf_token> --device insane input.mp4`

Note that transcribe-anything's CLI still expects the underscore because I didn't bother tracking down anything other than where the backend command gets built.

**Comment by zackees** [comment]
Fixed
