### ISSUE TITLE
Support for whisper.cpp?

### ISSUE THREAD

**Issue by daekian** [zackees/transcribe-anything#4]
Are there any plans for supporting [ggerganov's whisper.cpp](https://github.com/ggerganov/whisper.cpp) implementation of WhisperAI? 

transcribe-anything's ease of use and API + whisper.cpp's performance would be fantastic.

**Comment by zackees** [comment]
This is a fantastic idea.

I've wanted to do this but right now I'm busy with another (paid) project.

I'll accept a PR though to get this working.

**Comment by zackees** [comment]
Might be a good idea to have a python package called whisper.ai.cpp with builders for mac/linux/windows to prove it works on all platforms.

Then adding it would be a snap.

**Comment by zackees** [comment]
There are faster whisper implementations for cpu. Also I recommend that `--device insane` is used which works for Mac M1 using the `mps` device.
