### ISSUE TITLE
Module installation fail in local Blender python

### ISSUE THREAD

**Issue by tin2tin** [zackees/transcribe-anything#5]
Usually, running Blender as admin fixes problems of module installation, but not in this case: 
![image](https://user-images.githubusercontent.com/1322593/222704563-45300887-c43d-437f-8570-9c092068588d.png)

**Comment by tin2tin** [comment]
Is it a typo? onnxruntime-gpu?

**Comment by zackees** [comment]
I've never seen this before but I don't use blender.

Can you list your repro steps and then I can investigate and reproduce.

Also...
What Windows version are you using?
What python version?
What blender version?

Thanks!

**Comment by tin2tin** [comment]
I'll close this, as I've implemented whisper directly in my Blender add-on instead. Thanks.
